language: julia
arch:
  - amd64
os:
  - linux
  - osx
  - windows
notifications:
  email: false
branches:
  only:
  - master
julia:
  # - nightly
  - 1.0
  # - latest
jobs:
  allow_failures:
    - julia: latest
  include:
  - stage: "Documentation"
    julia: 1.0
    os: linux
    script:
      - julia --color=yes --project -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - julia --color=yes --project makedocs.jl
    after_success: skip
# after_success:
#   - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
#   - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
